# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'graduation project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for graduation project

pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'SwiftyMenu', '~> 0.5.1'
pod 'JTAppleCalendar', '~> 7.0'
 pod 'RealmSwift'
    pod 'SwipeCellKit'
    pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
end
